version: '3.8'

services:
  app:
    image: pavanilekkala123/springsqldockerjenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9098:9098"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dockerApplication
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dockerApplication
      MYSQL_ROOT_PASSWORD: pass@word1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
