server:
  port: 9098
spring:
  application:
    name: springsqldockerjenkins
  datasource:
    url: jdbc:mysql://localhost:3306/dockerApplication
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
